apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amuse-worker-scheduler-secrets
  namespace: amuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: amuse-azure-kv
  target:
    name: amuse-worker-scheduler-secrets
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: uit-amuse-postgres-connection-string
