apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amuse-redis
  namespace: amuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: amuse-azure-kv
  target:
    name: amuse-redis
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: amuse-redis-password
