apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amuse-api-secrets
  namespace: amuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: amuse-azure-kv
  target:
    name: amuse-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: uit-amuse-postgres-connection-string
    - secretKey: Jwt__SigningKey
      remoteRef:
        key: amuse-jwt-signing-key
    - secretKey: Media__Endpoint
      remoteRef:
        key: amuse-r2-endpoint
    - secretKey: Media__PublicBaseUrl
      remoteRef:
        key: amuse-r2-public-base-url
    - secretKey: Media__AccessKey
      remoteRef:
        key: amuse-r2-access-key
    - secretKey: Media__SecretKey
      remoteRef:
        key: amuse-r2-secret-key
    - secretKey: RabbitMq__Password
      remoteRef:
        key: amuse-rabbitmq-password
    - secretKey: Identity__Email__Smtp__Host
      remoteRef:
        key: amuse-smtp-host
    - secretKey: Identity__Email__Smtp__User
      remoteRef:
        key: amuse-smtp-user
    - secretKey: Identity__Email__Smtp__Password
      remoteRef:
        key: amuse-smtp-password
