apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: amuse
  namespace: argocd
spec:
  description: Amuse music platform workloads
  sourceRepos:
    - https://github.com/honguyenminh/amuse-deploy.git
  destinations:
    - namespace: amuse
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: gateway.networking.k8s.io
      kind: GatewayClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
