apiVersion: v1
kind: ConfigMap
metadata:
  name: amuse-api-env
  namespace: amuse
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  Identity__Email__Smtp__Enabled: "true"
  Identity__Email__Smtp__Host: "mailpit"
  Identity__Email__Smtp__Port: "1025"
  Identity__Email__Smtp__UseSsl: "false"
  Identity__Email__Smtp__FromAddress: "noreply@amuse.local"
  Identity__Email__Smtp__FromName: "Amuse"
  Media__Endpoint: "http://minio:9000"
  RabbitMq__HostName: "rabbitmq"
