apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - data/postgres.yaml
  - data/postgres-service.yaml
  - data/minio.yaml
  - data/minio-service.yaml
  - data/minio-init-job.yaml
  - secrets.example.yaml

configMapGenerator:
  - name: amuse-cluster-config
    envs:
      - config/cluster.env
    options:
      disableNameSuffixHash: true

replacements:
  - path: config/replacements.yaml

patches:
  - path: gateway-patch.yaml
  - path: tls-patch.yaml
  - path: hosts-patch.yaml
  - path: api-env-patch.yaml
  - path: workload-identity-patch.yaml
  - path: secrets-argo-patch.yaml

components:
  - images-tags
