apiVersion: v1
kind: Service
metadata:
  name: amuse-api
  namespace: amuse
  labels:
    app.kubernetes.io/name: amuse-api
    app.kubernetes.io/part-of: amuse
spec:
  selector:
    app.kubernetes.io/name: amuse-api
  ports:
    - name: http
      port: 80
      targetPort: http
