apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: amuse
  labels:
    app.kubernetes.io/name: consumer
    app.kubernetes.io/part-of: amuse
spec:
  selector:
    app.kubernetes.io/name: consumer
  ports:
    - name: http
      port: 3000
      targetPort: http
