apiVersion: v1
kind: ConfigMap
metadata:
  name: amuse-api-env
  namespace: amuse
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  Identity__Email__Smtp__Enabled: "true"
  Media__ForcePathStyle: "true"
  RabbitMq__HostName: "rabbitmq"
