apiVersion: v1
kind: ServiceAccount
metadata:
  name: amuse-api
  namespace: amuse
  annotations:
    azure.workload.identity/client-id: "REPLACE_ME"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amuse-worker-transcoder
  namespace: amuse
  annotations:
    azure.workload.identity/client-id: "REPLACE_ME"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amuse-worker-scheduler
  namespace: amuse
  annotations:
    azure.workload.identity/client-id: "REPLACE_ME"
  labels:
    azure.workload.identity/use: "true"
