apiVersion: v1
kind: ServiceAccount
metadata:
  name: amuse-api
  namespace: amuse
  labels:
    app.kubernetes.io/name: amuse-api
    app.kubernetes.io/part-of: amuse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amuse-worker-transcoder
  namespace: amuse
  labels:
    app.kubernetes.io/name: amuse-worker-transcoder
    app.kubernetes.io/part-of: amuse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amuse-worker-scheduler
  namespace: amuse
  labels:
    app.kubernetes.io/name: amuse-worker-scheduler
    app.kubernetes.io/part-of: amuse
